nubis/cloudformation/main.json
=> Switch stacks to v0.9.0 from master.

nubis/cloudformation/main.json
=> Add our own custom security group to allow fluent traffic inbound.

nubis/puppet/files/fluentd-fixups, nubis/puppet/init.pp
=> Add Startup fixups.

nubis/cloudformation/main.json, nubis/puppet/files/fluentd-fixups
=> Fixes for multiple VPCs / one-account

nubis/cloudformation/main.json
=> Add StacksVersion to VPCInfo call

nubis/puppet/files/confd/conf.d/fluentd-collector.toml, nubis/puppet/files/confd/templates/fluentd-collector.tmpl
Configuration options are now:
- SQS/Queue (queue name)
- SQS/AccessKey
- SQS/SecretKey
=> Add AWS API key support to SQS

nubis/cloudformation/main.json
=> Create the required policy for access to credstash's DynamoDB and the required KMS Key

nubis/cloudformation/main.json, nubis/puppet/files/confd/templates/fluentd-collector.tmpl
=> Enable Syslog listener, in case we need it

nubis/puppet/files/confd/conf.d/fluentd-collector.toml, nubis/puppet/files/confd/templates/fluentd-collector.tmpl, nubis/puppet/init.pp
=> Add support for AWS ElasticSearch

nubis/cloudformation/main.json
=> Add the Credstash Managed Policy to gain access to Platform secrets

nubis/cloudformation/main.json
=> Set Purpose=Fluent-Collector

nubis/puppet/files/confd/conf.d/fluentd-collector.toml, nubis/puppet/files/confd/templates/fluentd-collector.tmpl, nubis/puppet/files/fluent-startup, nubis/puppet/init.pp
=> Fill-in KV defaults with provided data

nubis/puppet/files/fluent-startup
=> Default ELB access logging bucket from user-data

.gitignore, nubis/Puppetfile, nubis/puppet/files/confd/templates/fluentd-collector.tmpl, nubis/puppet/init.pp
See: shinsaka/fluent-plugin-elb-log#18
Fixes #69
=> Fix proxy support, requires one upgrade and one monkey patch

nubis/Puppetfile, nubis/builder/project.json, nubis/puppet/init.pp
=> Upgrade to fluent-plugin-elb-log 0.2.6

nubis/puppet/init.pp
Annoyingly, this requires forked GEMs hosted on people.m.o for now.
Fixes #81
=> Fix ruby >= 2 dependencies by pinning back down some fluentd plugins

nubis/puppet/init.pp
This way, we can get rid of all the custom gems I had to create
Fixes #68
=> This upgrades us to td-agent 2.x

nubis/puppet/files/confd/templates/fluentd-collector.tmpl, nubis/puppet/init.pp
=> Install and enable Prometheus collector for Fluentd

nubis/puppet/init.pp
* s3 => 0.7.1 ( Fixes #61 )
* elasticsearch => 1.6.0
Fixes #100
=> Upgrade fluentd plugins

nubis/puppet/files/confd/templates/fluentd-collector.tmpl, nubis/puppet/files/fluent-startup, nubis/puppet/fluentd.pp, nubis/terraform/multi/input.tf, nubis/terraform/multi/main.tf
=> Enable log injection into ElasticSearch

nubis/puppet/files/confd/templates/fluentd-collector.tmpl
=> Increase ES timeout to 30s to account for batch submissions

.travis.yml, nubis/puppet/files/confd/conf.d/fluentd-collector.toml, nubis/puppet/files/confd/templates/fluentd-collector.tmpl, nubis/puppet/files/elasticsearch-logstash-template.json, nubis/puppet/fluentd.pp, nubis/terraform/multi/main.tf
=> Add an ES index template from logstash

nubis/puppet/files/confd/templates/fluentd-collector.tmpl
=> Disable reload_* knobs to avoid running the ES node discovery

nubis/puppet/files/confd/templates/fluentd-collector.tmpl
=> Tag plugin monitor metrics as forwardable events

nubis/puppet/files/confd/templates/fluentd-collector.tmpl, nubis/puppet/files/fluent-startup, nubis/terraform/multi/input.tf, nubis/terraform/multi/main.tf
As required by opsec
Fixes #122
=> Add support for pushing events into SQS

nubis/puppet/fluentd.pp
=> Upgrade outdated plugins

nubis/puppet/files/fluent-startup
=> Register/De-Register an external Consul for ES

nubis/puppet/elasticsearch_exporter.pp
=> Run a Prometheus ES Exporter on tcp/9105

nubis/puppet/files/confd/templates/fluentd-collector.tmpl
=> Shrink down S3 time slices to hourly

nubis/terraform/multi/main.tf
=> Disabled EC2 detailled monitoring

nubis/terraform/multi/input.tf, nubis/terraform/multi/main.tf
Allow member of the SSO SG to access our ES proxy
=> Add support for SSO security group

nubis/puppet/files/confd/templates/fluentd-collector.tmpl, nubis/puppet/fluentd.pp, nubis/terraform/multi/input.tf, nubis/terraform/multi/main.tf
=> Performance improvements, allows instance_type to be configurable

nubis/puppet/aws-proxy.pp
Use upstream package, fixes issue #198
=> Use upstream aws-proxy

nubis/terraform/main.tf
=> Get rid of Atlas

nubis/puppet/curator.pp, nubis/puppet/files/nubis-cleanup-es-indices
=> Fix curator for ES 5.x

nubis/puppet/elasticsearch_exporter.pp
=> Upgraded elasticsearch exporter

nubis/terraform/main.tf
=> Destroy unicreds resources

nubis/puppet/files/nubis-cleanup-es-indices
=> Be more specific about PATH

nubis/files/confd/templates/fluentd-collector.tmpl, nubis/files/elasticsearch-logstash-template.json, nubis/files/fluent-startup, nubis/puppet/fluentd.pp
This required upgrading many plugins and forking 2 for now.
Fixes #243
=> Upgrade to TD-Agent 3, getting fluentd 1.x

nubis/files/confd/templates/fluentd-collector.tmpl, nubis/files/fluent-startup
=> [ELB] Ingest only logs that are newer than our startup time

nubis/files/fluent-startup
=> Use systemctl consistently

nubis/puppet/aws-proxy.pp, nubis/puppet/elasticsearch_exporter.pp, nubis/puppet/fluentd.pp, nubis/terraform/input.tf, nubis/terraform/main.tf
=> Linting fix

nubis/builder/project.json
Fixes issue #259, merge #260 before merging this
=> Tag this project as a platform component

nubis/puppet/fluentd.pp
=> Inhibit td-agent restart during builds
